app = 'chatapp-fly'
primary_region = 'ams'

[build]
app = "chat-app"
primary_region = "fra"


[env]
  NODE_ENV = "production"
  PORT = "3001"


[http_service]
  internal_port = 3001
  force_https = true

  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

[checks]
  [checks.http]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "2s"
